#ifndef INCLUDE_FILE_FOR_DISPLAY_TECHNOLOGY
#define INCLUDE_FILE_FOR_DISPLAY_TECHNOLOGY

typedef enum
{
	DISPLAY_TECHNOLOGY_UNKNOWN = -1
	,DISPLAY_TECHNOLOGY_CRT = 0
	,DISPLAY_TECHNOLOGY_LCD
	,DISPLAY_TECHNOLOGY_PROJECTOR_REAR
	,DISPLAY_TECHNOLOGY_PROJECTOR_FRONT
} DISPLAY_TECHNOLOGY;

#endif
