/*
 *  LEDControl.h
 *
 *  Created by Ben Guthro on Fri Feb 25 2005.
 *  Copyright (c) 2005 gmb. All rights reserved.
 *
 */
#ifndef __LEDANIMCONTROL_H__
#define __LEDANIMCONTROL_H__

typedef enum 
{
	ALED_ALL_ON = 0,
	ALED_ALL_OFF,
	
	ALED_SWEEP_UP,
	ALED_SWEEP_DOWN,
	
	ALED_CHASE_UP,
	ALED_CHASE_DOWN,
	
	ALED_PULSE_UP,
	ALED_PULSE_DOWN,
	
	ALED_MARCH_ANTS,
	
	ALED_BLINK_ONE,
	ALED_BLINK_TWO,
	ALED_BLINK_THREE,
	ALED_BLINK_FOUR,
	
	ALED_PULSE_UP_ONE,
	ALED_PULSE_UP_TWO,
	ALED_PULSE_UP_THREE,
	ALED_PULSE_UP_FOUR,
	
	ALED_PULSE_DOWN_ONE,
	ALED_PULSE_DOWN_TWO,
	ALED_PULSE_DOWN_THREE,
	ALED_PULSE_DOWN_FOUR,
	
	ALED_CHASE_UP_ONE,
	ALED_CHASE_UP_TWO,
	ALED_CHASE_UP_THREE,
	ALED_CHASE_UP_FOUR,
	
	ALED_CHASE_DOWN_ONE,
	ALED_CHASE_DOWN_TWO,
	ALED_CHASE_DOWN_THREE,
	ALED_CHASE_DOWN_FOUR,
	
	ALED_SWEEP_UP_ONE,
	ALED_SWEEP_UP_TWO,
	ALED_SWEEP_UP_THREE,
	ALED_SWEEP_UP_FOUR,
	
	ALED_SWEEP_DOWN_ONE,
	ALED_SWEEP_DOWN_TWO,
	ALED_SWEEP_DOWN_THREE,
	ALED_SWEEP_DOWN_FOUR
	
} ALED_ANIMATION;

//speed in usec to wait between ops
typedef enum
{
	ALED_REALLYSLOW		= 320000,
	ALED_SLOW			= 160000,
	ALED_MEDSLOW		= 135000,
	ALED_MED			= 90000,
	ALED_MEDFAST		= 45000,
	ALED_FAST			= 20000
} ALED_ANIM_SPEED;

class CGenericCalibrator;

bool AnimateCalibratorLED(CGenericCalibrator*, ALED_ANIMATION, ALED_ANIM_SPEED);

#endif