#ifndef OSDSTRUCTURES_H_INCLUDED
#define OSDSTRUCTURES_H_INCLUDED

#define MAX_CONTROL_LABEL_LENGTH 24
#define MAX_COLOR_CONTROLS 8
#define MAX_GEOMETRY_CONTROLS 11
#define MAX_IMAGE_CONTROLS 11
#define MAX_FRINGE_CONTROLS 6

#ifndef OSD_MAX_CONTROLS
#define OSD_MAX_CONTROLS 16
#endif

#include "dmc.h"

typedef enum {OSD_NONE  = 0,
              OSD_COLOR = 1,
			  OSD_GEOMETRY=2, 
			  OSD_IMAGE=3, 
			  OSD_FRINGING=4
			  } OSD_TYPE;

typedef struct {
	char *windowTitle;
	char *resetTitle;
	int numActiveControls;
	char *controlTitle[OSD_MAX_CONTROLS];
	short originalControlValue[OSD_MAX_CONTROLS];
	short controlValue[OSD_MAX_CONTROLS];
	short maxValue[OSD_MAX_CONTROLS];
	DMC_CONTROL_INDEX dmpiCode[OSD_MAX_CONTROLS];
	//int controlTitleID[OSD_MAX_CONTROLS];
	bool nonStandardControl[OSD_MAX_CONTROLS];
} SLIDER_DESCRIPTION;

#ifndef WIN32
#ifndef IDS_LABEL_BRIGHTNESS // Define IDS if not found in resource file.
typedef enum {
	IDS_LABEL_BRIGHTNESS,
	IDS_LABEL_CONTRAST,
    IDS_LABEL_RED_GAIN,
    IDS_LABEL_GREEN_GAIN,
    IDS_LABEL_BLUE_GAIN,
    IDS_LABEL_RED_BLACK_LEVEL,
    IDS_LABEL_GREEN_BLACK_LEVEL,
    IDS_LABEL_BLUE_BLACK_LEVEL,
    IDS_LABEL_HSIZE,
    IDS_LABEL_HPOS,
    IDS_LABEL_VSIZE,
    IDS_LABEL_VPOS,
    IDS_LABEL_PINCUSHION,
    IDS_LABEL_PINBALANCE,
    IDS_LABEL_TILT,
    IDS_LABEL_HPAR_DISTORTION,
	IDS_LABEL_VPAR_DISTORTION,
    IDS_LABEL_HKEYSTONE,
	IDS_LABEL_VKEYSTONE,
	IDS_LABEL_VERT_CONVRB,
	IDS_LABEL_VERT_CONVMG,
	IDS_LABEL_HORIZ_CONVRB,
	IDS_LABEL_HORIZ_CONVMG,
    IDS_LABEL_V_LINEARITY,
    IDS_LABEL_V_LIN_BALANCE,
    IDS_LABEL_TOP_CORNER_DIST,
    IDS_LABEL_TOP_CORNER_BALANCE,
    IDS_LABEL_BOTTOM_CORNER_DIST,
    IDS_LABEL_BOTTOM_CORNER_BALANCE,
    IDS_LABEL_MOIRE_CANCEL,
    IDS_IMAGE_SETTINGS,
    IDS_LABEL_RESTORE,
    IDS_LABEL_RESET_COLOR,
    IDS_LABEL_RESET_GEOMETRY,
    IDS_LABEL_RESET_IMAGE,
    IDS_GEOMETRY_SETTINGS, 
    IDS_RESTORE_ORIGINAL_QUERY,
    IDS_COLOR_SETTINGS,
	IDS_LABEL_MAX_RED_GAIN,
	IDS_LABEL_MAX_GREEN_GAIN,
	IDS_LABEL_MAX_BLUE_GAIN,
	IDS_LABEL_MAX_RED_BIAS,
	IDS_LABEL_MAX_GREEN_BIAS,
	IDS_LABEL_MAX_BLUE_BIAS,
	IDS_LABEL_FRINGING_SETTINGS,
	IDS_LABEL_RESET_FRINGING
    
} OSD_IDS_LABEL_ENUM;
#endif

typedef struct {short ident; char *str;} STRING_MAP;

#define STRINGMAP_SIZE 50
extern STRING_MAP siStringMap[STRINGMAP_SIZE];


#endif // end of work-around for Mac

// COLOR SLIDER CONTROL STUFF
extern SLIDER_DESCRIPTION ColorSliderDescription;
extern char controlNameColor[MAX_COLOR_CONTROLS][MAX_CONTROL_LABEL_LENGTH];

//GEOMETRY SLIDER CONTROL STUFF
extern SLIDER_DESCRIPTION GeometrySliderDescription;
extern char controlNameGeometry[MAX_GEOMETRY_CONTROLS][MAX_CONTROL_LABEL_LENGTH];

// IMAGE SLIDER CONTROL STUFF
extern SLIDER_DESCRIPTION ImageSliderDescription;
extern char controlNameImage[MAX_IMAGE_CONTROLS][MAX_CONTROL_LABEL_LENGTH];

// FRINGE SLIDER CONTROL STUFF
extern SLIDER_DESCRIPTION FringeSliderDescription;
extern char controlNameFringe[MAX_FRINGE_CONTROLS][MAX_CONTROL_LABEL_LENGTH];

#endif
